# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 19:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('principals', models.FloatField(default=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('subtitutedOn', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('subtitutedOff', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('yellowCards', models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('doubleYellowCards', models.IntegerField(default=-3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('redCards', models.FloatField(default=-6, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('penaltyGoals', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('concededGoald', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('mathesWithoutGoals', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('goalkeeper_goals', models.FloatField(default=6, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('goalkeeper_assists', models.FloatField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('goalkeeper_ownGoals', models.FloatField(default=-6, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('goalkeeper_minutesPorGoal', models.FloatField(default=-0.5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('defence_goals', models.FloatField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('defence_assists', models.FloatField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('defence_ownGoals', models.FloatField(default=-5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('defence_minutesPorGoal', models.FloatField(default=-1.5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('midfield_goals', models.FloatField(default=4.5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('midfield_assists', models.FloatField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('midfield_ownGoals', models.FloatField(default=-3.5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('midfield_minutesPorGoal', models.FloatField(default=-2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('striker_goals', models.FloatField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('striker_assists', models.FloatField(default=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('striker_ownGoals', models.FloatField(default=-3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('striker_minutesPorGoal', models.FloatField(default=-3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-10)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 14, 21, 2, 26, 381710)),
        ),
    ]
