# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20170516_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 16, 17, 20, 25, 327191)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='perfil.png', null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
