# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 17:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
