# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 17:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('badge', models.URLField(null=True, validators=[django.core.validators.URLValidator()])),
                ('squad', models.IntegerField(null=True)),
                ('avgAge', models.IntegerField(null=True)),
                ('foreignCount', models.IntegerField(null=True)),
                ('value', models.FloatField(null=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout.Championship')),
            ],
        ),
    ]
