# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(null=True)),
                ('movingFrom', models.CharField(max_length=100, null=True)),
                ('movingTo', models.CharField(max_length=100, null=True)),
                ('value', models.FloatField(null=True)),
                ('cost', models.CharField(max_length=150, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout.Player')),
            ],
        ),
    ]
