# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0004_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('championship', models.CharField(max_length=150)),
                ('club', models.CharField(blank=True, max_length=150)),
                ('squad', models.IntegerField(null=True)),
                ('principal', models.IntegerField(null=True)),
                ('pointsPerMatch', models.FloatField(null=True)),
                ('goals', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('ownGoals', models.IntegerField(null=True)),
                ('subtitutedOn', models.IntegerField(null=True)),
                ('subtitutedOff', models.IntegerField(null=True)),
                ('yellowCards', models.IntegerField(null=True)),
                ('doubleYellowCards', models.IntegerField(null=True)),
                ('redCards', models.IntegerField(null=True)),
                ('penaltyGoals', models.IntegerField(null=True)),
                ('minutesPorGoal', models.FloatField(null=True)),
                ('minutesPlayed', models.IntegerField(null=True)),
                ('concededGoald', models.IntegerField(null=True)),
                ('mathesWithoutGoals', models.IntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout.Player')),
            ],
        ),
    ]
