# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scout', '0005_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sin título', max_length=150)),
                ('value', models.FloatField(default=0.0)),
                ('averageAge', models.IntegerField(default=0)),
                ('likeCount', models.IntegerField(default=0)),
                ('description', models.TextField(default='Sin descripción')),
                ('lastUpdate', models.DateField(blank=True, null=True)),
                ('players', models.ManyToManyField(related_name='players', to='scout.Player')),
                ('principals', models.ManyToManyField(related_name='principals', to='scout.Player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout.Squad'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
