# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0007_auto_20170514_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
